name: exam_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  pinput: ^5.0.1
  shared_preferences: ^2.5.1
  injectable: ^2.5.0
  internet_connection_checker: ^3.0.1
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  either_dart: ^1.0.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  injectable_generator: ^2.7.0
  freezed: ^2.5.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
